/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FrankaFORCESNLPsolver_model_ ## ID
#endif

#include <math.h> 
#include "FrankaFORCESNLPsolver_model.h"

#ifndef casadi_real
#define casadi_real FrankaFORCESNLPsolver_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s4[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s5[11] = {2, 4, 0, 1, 2, 3, 4, 0, 1, 0, 1};
static const casadi_int casadi_s6[9] = {1, 4, 0, 0, 0, 1, 2, 0, 0};
static const casadi_int casadi_s7[9] = {1, 4, 0, 1, 2, 2, 2, 0, 0};

/* FrankaFORCESNLPsolver_objective_0:(i0[4],i1[8])->(o0,o1[1x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=10.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1-a2);
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][3] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a3=(a3-a4);
  a4=casadi_sq(a3);
  a2=(a2+a4);
  a2=(a0*a2);
  a4=arg[0]? arg[0][0] : 0;
  a5=casadi_sq(a4);
  a6=arg[0]? arg[0][1] : 0;
  a7=casadi_sq(a6);
  a5=(a5+a7);
  a2=(a2+a5);
  if (res[0]!=0) res[0][0]=a2;
  a4=(a4+a4);
  if (res[1]!=0) res[1][0]=a4;
  a6=(a6+a6);
  if (res[1]!=0) res[1][1]=a6;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[1]!=0) res[1][2]=a1;
  a3=(a3+a3);
  a0=(a0*a3);
  if (res[1]!=0) res[1][3]=a0;
  return 0;
}

int FrankaFORCESNLPsolver_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

int FrankaFORCESNLPsolver_objective_0_alloc_mem(void) {
  return 0;
}

int FrankaFORCESNLPsolver_objective_0_init_mem(int mem) {
  return 0;
}

void FrankaFORCESNLPsolver_objective_0_free_mem(int mem) {
}

int FrankaFORCESNLPsolver_objective_0_checkout(void) {
  return 0;
}

void FrankaFORCESNLPsolver_objective_0_release(int mem) {
}

void FrankaFORCESNLPsolver_objective_0_incref(void) {
}

void FrankaFORCESNLPsolver_objective_0_decref(void) {
}

casadi_int FrankaFORCESNLPsolver_objective_0_n_in(void) { return 2;}

casadi_int FrankaFORCESNLPsolver_objective_0_n_out(void) { return 2;}

casadi_real FrankaFORCESNLPsolver_objective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FrankaFORCESNLPsolver_objective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FrankaFORCESNLPsolver_objective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FrankaFORCESNLPsolver_objective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FrankaFORCESNLPsolver_objective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

int FrankaFORCESNLPsolver_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FrankaFORCESNLPsolver_dynamics_0:(i0[4],i1[8])->(o0[2],o1[2x4,4nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[0]? arg[0][2] : 0;
  a1=arg[0]? arg[0][0] : 0;
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][1] : 0;
  a0=(a0+a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=1.;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[1]!=0) res[1][3]=a0;
  return 0;
}

int FrankaFORCESNLPsolver_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

int FrankaFORCESNLPsolver_dynamics_0_alloc_mem(void) {
  return 0;
}

int FrankaFORCESNLPsolver_dynamics_0_init_mem(int mem) {
  return 0;
}

void FrankaFORCESNLPsolver_dynamics_0_free_mem(int mem) {
}

int FrankaFORCESNLPsolver_dynamics_0_checkout(void) {
  return 0;
}

void FrankaFORCESNLPsolver_dynamics_0_release(int mem) {
}

void FrankaFORCESNLPsolver_dynamics_0_incref(void) {
}

void FrankaFORCESNLPsolver_dynamics_0_decref(void) {
}

casadi_int FrankaFORCESNLPsolver_dynamics_0_n_in(void) { return 2;}

casadi_int FrankaFORCESNLPsolver_dynamics_0_n_out(void) { return 2;}

casadi_real FrankaFORCESNLPsolver_dynamics_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FrankaFORCESNLPsolver_dynamics_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FrankaFORCESNLPsolver_dynamics_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FrankaFORCESNLPsolver_dynamics_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FrankaFORCESNLPsolver_dynamics_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

int FrankaFORCESNLPsolver_dynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FrankaFORCESNLPsolver_inequalities_0:(i0[4],i1[8])->(o0,o1[1x4,2nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[0]? arg[0][2] : 0;
  a1=arg[1]? arg[1][4] : 0;
  a0=(a0-a1);
  a1=casadi_sq(a0);
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[1]? arg[1][5] : 0;
  a2=(a2-a3);
  a3=casadi_sq(a2);
  a1=(a1+a3);
  a1=sqrt(a1);
  if (res[0]!=0) res[0][0]=a1;
  a0=(a0/a1);
  if (res[1]!=0) res[1][0]=a0;
  a2=(a2/a1);
  if (res[1]!=0) res[1][1]=a2;
  return 0;
}

int FrankaFORCESNLPsolver_inequalities_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

int FrankaFORCESNLPsolver_inequalities_0_alloc_mem(void) {
  return 0;
}

int FrankaFORCESNLPsolver_inequalities_0_init_mem(int mem) {
  return 0;
}

void FrankaFORCESNLPsolver_inequalities_0_free_mem(int mem) {
}

int FrankaFORCESNLPsolver_inequalities_0_checkout(void) {
  return 0;
}

void FrankaFORCESNLPsolver_inequalities_0_release(int mem) {
}

void FrankaFORCESNLPsolver_inequalities_0_incref(void) {
}

void FrankaFORCESNLPsolver_inequalities_0_decref(void) {
}

casadi_int FrankaFORCESNLPsolver_inequalities_0_n_in(void) { return 2;}

casadi_int FrankaFORCESNLPsolver_inequalities_0_n_out(void) { return 2;}

casadi_real FrankaFORCESNLPsolver_inequalities_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FrankaFORCESNLPsolver_inequalities_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FrankaFORCESNLPsolver_inequalities_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FrankaFORCESNLPsolver_inequalities_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FrankaFORCESNLPsolver_inequalities_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s6;
    default: return 0;
  }
}

int FrankaFORCESNLPsolver_inequalities_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FrankaFORCESNLPsolver_objective_1:(i0[4],i1[8])->(o0,o1[1x4,2nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=10.;
  a1=arg[0]? arg[0][0] : 0;
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][1] : 0;
  a4=casadi_sq(a3);
  a2=(a2+a4);
  a2=(a0*a2);
  if (res[0]!=0) res[0][0]=a2;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[1]!=0) res[1][0]=a1;
  a3=(a3+a3);
  a0=(a0*a3);
  if (res[1]!=0) res[1][1]=a0;
  return 0;
}

int FrankaFORCESNLPsolver_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

int FrankaFORCESNLPsolver_objective_1_alloc_mem(void) {
  return 0;
}

int FrankaFORCESNLPsolver_objective_1_init_mem(int mem) {
  return 0;
}

void FrankaFORCESNLPsolver_objective_1_free_mem(int mem) {
}

int FrankaFORCESNLPsolver_objective_1_checkout(void) {
  return 0;
}

void FrankaFORCESNLPsolver_objective_1_release(int mem) {
}

void FrankaFORCESNLPsolver_objective_1_incref(void) {
}

void FrankaFORCESNLPsolver_objective_1_decref(void) {
}

casadi_int FrankaFORCESNLPsolver_objective_1_n_in(void) { return 2;}

casadi_int FrankaFORCESNLPsolver_objective_1_n_out(void) { return 2;}

casadi_real FrankaFORCESNLPsolver_objective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FrankaFORCESNLPsolver_objective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FrankaFORCESNLPsolver_objective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FrankaFORCESNLPsolver_objective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FrankaFORCESNLPsolver_objective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s7;
    default: return 0;
  }
}

int FrankaFORCESNLPsolver_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FrankaFORCESNLPsolver_inequalities_1:(i0[4],i1[8])->(o0,o1[1x4,2nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[0]? arg[0][2] : 0;
  a1=arg[1]? arg[1][4] : 0;
  a0=(a0-a1);
  a1=casadi_sq(a0);
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[1]? arg[1][5] : 0;
  a2=(a2-a3);
  a3=casadi_sq(a2);
  a1=(a1+a3);
  a1=sqrt(a1);
  if (res[0]!=0) res[0][0]=a1;
  a0=(a0/a1);
  if (res[1]!=0) res[1][0]=a0;
  a2=(a2/a1);
  if (res[1]!=0) res[1][1]=a2;
  return 0;
}

int FrankaFORCESNLPsolver_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

int FrankaFORCESNLPsolver_inequalities_1_alloc_mem(void) {
  return 0;
}

int FrankaFORCESNLPsolver_inequalities_1_init_mem(int mem) {
  return 0;
}

void FrankaFORCESNLPsolver_inequalities_1_free_mem(int mem) {
}

int FrankaFORCESNLPsolver_inequalities_1_checkout(void) {
  return 0;
}

void FrankaFORCESNLPsolver_inequalities_1_release(int mem) {
}

void FrankaFORCESNLPsolver_inequalities_1_incref(void) {
}

void FrankaFORCESNLPsolver_inequalities_1_decref(void) {
}

casadi_int FrankaFORCESNLPsolver_inequalities_1_n_in(void) { return 2;}

casadi_int FrankaFORCESNLPsolver_inequalities_1_n_out(void) { return 2;}

casadi_real FrankaFORCESNLPsolver_inequalities_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FrankaFORCESNLPsolver_inequalities_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FrankaFORCESNLPsolver_inequalities_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FrankaFORCESNLPsolver_inequalities_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FrankaFORCESNLPsolver_inequalities_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s6;
    default: return 0;
  }
}

int FrankaFORCESNLPsolver_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
